#!/bin/sh
# http://unlicense.org/

# optional variables to set before sourcing this script
#
# - W_VTE_IS_OPTIONAL=yes [show --disable-vte in --help msg]
# - W_VTE_MIN_VERSION=xxx [minimun supported version]
#

#=======================================
apps_to_check="$apps_to_check vte"
extra_env_vars="$extra_env_vars VTE"
extra_configure_opts="$extra_configure_opts vte"
#=======================================

vte_pc_pkg="vte vte-2.91"


opt_print_vte()
{
	if [ "$W_VTE_IS_OPTIONAL" = "yes" ] ; then
		echo "  --disable-vte           do not build VTE support (autodetect)"
	fi
}


opt_configure_vte()
{
	if [ "$W_VTE_IS_OPTIONAL" = "yes" ] ; then
		enable_vte=check
	else
		enable_vte=yes
		return
	fi

	for i in $@
	do
		case $i in
		--enable-vte)  enable_vte=yes ;;
		--disable-vte) enable_vte=no ;;
		esac
	done
}


opt_check_vte()
{
	if [ "$enable_vte" = "no" ] ; then
		return
	fi

	if [ -n "$VTE_CFLAGS" ] || [ -n "$VTE_LIBS" ] ; then
		echo "Checking for VTE... \$VTE_CFLAGS/\$VTE_LIBS"
	else
		pcpkg=
		for onepkg in ${vte_pc_pkg}
		do
			if w_pkgconfig_check ${onepkg} ${W_VTE_MIN_VERSION} ; then
				pcpkg=${onepkg}
				break
			fi
		done

		if [ -z "$pcpkg" ] ; then
			if [ "$enable_vte" = "yes" ] ; then
				exit_error "pkg-config: vte was not found"
			fi
			return
		fi
		if [ ! -f "$pcpkg" ] ; then
			# $pcpkg must not be a file, otherwise it is a custom xxx-config file
			VTE_CFLAGS="$(run_pkg_config ${pcpkg} --cflags 2>/dev/null)"
			VTE_LIBS="$(run_pkg_config ${pcpkg} --libs 2>/dev/null)"
		fi
	fi

	config_h_have="$config_h_have VTE"
	config_mk_flags="$config_mk_flags VTE"
}

